### ISSUE TITLE
Contribution Guide and Readme

### ISSUE THREAD

**Issue by canarado** [IllusionMan1212/twatter-react#3]
A contribution guide and a proper readme with deployment instructions could be quite beneficial for you!

**Comment by canarado** [comment]
I am filing a class A lawsuit to take over twatter and force a contribution guide. Better hire some lawyers son.

**Comment by Sv443** [comment]
bog

**Comment by canarado** [comment]
danoff

**Comment by IllusionMan1212** [comment]
im closing its source soon so yall can suck it.

**Comment by Sv443** [comment]
rude

**Comment by IllusionMan1212** [comment]
decided to not close the source. better readme and hopefully a contribution guide soon

**Comment by canarado** [comment]
😍😍

**Comment by Sv443** [comment]
> decided to not close the source. better readme and hopefully a contribution guide soon

I'm literally crying and pissing everywhere

**Comment by canarado** [comment]
Illusion is complying with our request, so we do not need to harass him any longer.
