### ISSUE TITLE
Transparent images shouldn't have a background

### ISSUE THREAD

**Issue by Sv443** [IllusionMan1212/twatter-react#6]
This is how it currently looks:
  
![grafik](https://user-images.githubusercontent.com/38158426/135041951-703a404b-461d-45f8-b02d-f12cfeaed298.png)
  
Look at this, such a beautiful and transparent and round boi:  
 
![he_round](https://user-images.githubusercontent.com/38158426/135042005-7bab0ad8-9416-4dc7-82c5-902a679c7a2f.png)

**Comment by IllusionMan1212** [comment]
working on this right now!

**Comment by IllusionMan1212** [comment]
fixed by https://github.com/illusionman1212/twatter-react/commit/461015aec336a041d68c0e0e7c37cf57ab250e68 :tada:
